# Generated by Django 4.1.1 on 2022-09-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='key',
        ),
    ]
