# Generated by Django 4.1.1 on 2022-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0003_alter_images_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
