# Generated by Django 4.1.1 on 2022-09-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0004_images_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='images_db',
        ),
    ]
